#include "../../core/backend.h"

/* @generated by tools/gen_ops.c; do not edit. */

gd_status gd_backend_relu(gd_backend *backend,
                          const gd_backend_tensor_view *x,
                          const gd_backend_tensor_view *y)
{
    (void)backend;
    (void)x;
    (void)y;
    return GD_ERR_UNSUPPORTED;
}

gd_status gd_backend_relu_backward(gd_backend *backend,
                                   const gd_backend_tensor_view *x,
                                   const gd_backend_tensor_view *grad_out,
                                   const gd_backend_tensor_view *grad_x)
{
    (void)backend;
    (void)x;
    (void)grad_out;
    (void)grad_x;
    return GD_ERR_UNSUPPORTED;
}

gd_status gd_backend_add(gd_backend *backend,
                          const gd_backend_tensor_view *x,
                          const gd_backend_tensor_view *y,
                          const gd_backend_tensor_view *out)
{
    (void)backend;
    (void)x;
    (void)y;
    (void)out;
    return GD_ERR_UNSUPPORTED;
}

gd_status gd_backend_mul(gd_backend *backend,
                          const gd_backend_tensor_view *x,
                          const gd_backend_tensor_view *y,
                          const gd_backend_tensor_view *out)
{
    (void)backend;
    (void)x;
    (void)y;
    (void)out;
    return GD_ERR_UNSUPPORTED;
}

gd_status gd_backend_sub(gd_backend *backend,
                          const gd_backend_tensor_view *x,
                          const gd_backend_tensor_view *y,
                          const gd_backend_tensor_view *out)
{
    (void)backend;
    (void)x;
    (void)y;
    (void)out;
    return GD_ERR_UNSUPPORTED;
}

gd_status gd_backend_sigmoid(gd_backend *backend,
                          const gd_backend_tensor_view *x,
                          const gd_backend_tensor_view *y)
{
    (void)backend;
    (void)x;
    (void)y;
    return GD_ERR_UNSUPPORTED;
}

gd_status gd_backend_sigmoid_backward(gd_backend *backend,
                                   const gd_backend_tensor_view *x,
                                   const gd_backend_tensor_view *grad_out,
                                   const gd_backend_tensor_view *grad_x)
{
    (void)backend;
    (void)x;
    (void)grad_out;
    (void)grad_x;
    return GD_ERR_UNSUPPORTED;
}

