#ifndef GRADIENTS_OPS_GENERATED_H
#define GRADIENTS_OPS_GENERATED_H

/* @generated by tools/gen_ops.c; do not edit. */

#include <gradients/status.h>
#include <gradients/tensor.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Direct backward helpers accept NULL grad_* output pointers to omit gradients.
 * If every grad_* output is NULL, helpers validate inputs/grad_out and return
 * GD_OK without enqueueing backward work. Requesting gradients for
 * non-differentiable inputs still returns GD_ERR_UNSUPPORTED. */

gd_status gd_relu(gd_context *ctx,
                  const gd_tensor *x,
                  gd_tensor *out);

gd_status gd_relu_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x);

gd_status gd_add(gd_context *ctx,
                  const gd_tensor *x,
                  const gd_tensor *y,
                  gd_tensor *out);

gd_status gd_add_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *y,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x,
                           gd_tensor *grad_y);

gd_status gd_mul(gd_context *ctx,
                  const gd_tensor *x,
                  const gd_tensor *y,
                  gd_tensor *out);

gd_status gd_mul_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *y,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x,
                           gd_tensor *grad_y);

gd_status gd_sub(gd_context *ctx,
                  const gd_tensor *x,
                  const gd_tensor *y,
                  gd_tensor *out);

gd_status gd_sub_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *y,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x,
                           gd_tensor *grad_y);

gd_status gd_reduce_mean(gd_context *ctx,
                  const gd_tensor *x,
                  gd_tensor *out);

gd_status gd_reduce_mean_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x);

gd_status gd_reduce_sum(gd_context *ctx,
                  const gd_tensor *x,
                  gd_tensor *out);

gd_status gd_reduce_sum_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x);

gd_status gd_cross_entropy(gd_context *ctx,
                  const gd_tensor *x,
                  const gd_tensor *y,
                  gd_tensor *out);

gd_status gd_cross_entropy_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *y,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x,
                           gd_tensor *grad_y);

gd_status gd_sigmoid(gd_context *ctx,
                  const gd_tensor *x,
                  gd_tensor *out);

gd_status gd_sigmoid_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x);

gd_status gd_mse(gd_context *ctx,
                  const gd_tensor *x,
                  const gd_tensor *y,
                  gd_tensor *out);

gd_status gd_mse_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *y,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x,
                           gd_tensor *grad_y);

gd_status gd_huber(gd_context *ctx,
                  const gd_tensor *x,
                  const gd_tensor *y,
                  gd_tensor *out);

gd_status gd_huber_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *y,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x,
                           gd_tensor *grad_y);

gd_status gd_dropout(gd_context *ctx,
                  const gd_tensor *x,
                  float p,
                  bool training,
                  uint64_t seed,
                  gd_tensor *out);

gd_status gd_dropout_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *grad_out,
                           float p,
                           uint64_t seed,
                           gd_tensor *grad_x);

gd_status gd_tanh(gd_context *ctx,
                  const gd_tensor *x,
                  gd_tensor *out);

gd_status gd_tanh_backward(gd_context *ctx,
                           const gd_tensor *x,
                           const gd_tensor *grad_out,
                           gd_tensor *grad_x);

#ifdef __cplusplus
}
#endif

#endif /* GRADIENTS_OPS_GENERATED_H */
