#include "../grad_impl.h"

/* Autogenerated scaffold. TODO: implement backward rule for `concat`. */
static gd_status concat_backward(_gd_bwd_ctx *b, const _gd_node *node)
{
    (void)b;
    (void)node;
    return _gd_error(GD_ERR_UNSUPPORTED,
                     "Autogenerated stub: op 'concat' backward rule not implemented; TODO fill src/ops/concat/grad_concat.c");
}

const _gd_bwd_rule _gd_bwd_rule_concat = {
    .op = _GD_OP_CONCAT,
    .fn = concat_backward,
    .unsupported_reason = NULL,
};
