#import "../../backends/metal/metal_op.h"

/* Autogenerated scaffold. TODO: implement `concat` Metal encoder. */
static gd_status concat_encode(_gd_metal_encode_ctx *ctx)
{
    (void)ctx;
    return _gd_error(GD_ERR_UNSUPPORTED,
                     "Autogenerated stub: op 'concat' Metal forward not implemented; TODO fill src/ops/concat/metal_concat.m");
}

const _gd_metal_op _gd_metal_op_concat = {
    .kind = _GD_OP_CONCAT,
    .name = "concat",
    .support = _gd_metal_support_default,
    .encode = concat_encode,
};
