#include "metal_common.metal"

/* Autogenerated scaffold. TODO: implement `gd_concat` Metal shader.
 * Host encoder currently returns GD_ERR_UNSUPPORTED, so this kernel is not called. */
kernel void gd_concat(uint gid [[thread_position_in_grid]])
{
    (void)gid;
}
