#!/usr/bin/env python3
# /// script
# dependencies = ["torch>=2.3", "numpy>=1.26"]
# ///
"""Compare gradients.c fp16 op forward/backward outputs against PyTorch refs.

Builds tools/gradients-ref-harness, feeds it the exact fp16 inputs generated by
PyTorch, then compares forward outputs and leaf grads.
"""

from __future__ import annotations

import argparse
import math
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import numpy as np
import torch
import torch.nn.functional as F


ROOT = Path(__file__).resolve().parents[2]
TOOL = ROOT / "build" / "tools" / "gradients-ref-harness"


@dataclass(frozen=True)
class Case:
    name: str
    op: str
    run: Callable[[Path, torch.device], int]


def pick_device(name: str) -> torch.device:
    if name != "auto":
        return torch.device(name)
    if torch.cuda.is_available():
        return torch.device("cuda")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def write_raw(root: Path, name: str, arr: np.ndarray) -> None:
    a = np.ascontiguousarray(arr)
    a.tofile(root / f"{name}.bin")


def read_raw(root: Path, name: str, dtype: np.dtype, shape: tuple[int, ...]) -> np.ndarray:
    arr = np.fromfile(root / f"{name}.bin", dtype=dtype)
    return arr.reshape(shape)


def rel_err(act: np.ndarray, exp: np.ndarray) -> float:
    a = act.astype(np.float64, copy=False)
    e = exp.astype(np.float64, copy=False)
    denom = np.maximum(np.maximum(np.abs(a), np.abs(e)), 1e-12)
    return float(np.max(np.abs(a - e) / denom)) if e.size else 0.0


def compare_arrays(case: str, refs: dict[str, np.ndarray], got: dict[str, np.ndarray],
                   atol: float, rtol: float) -> int:
    failures = 0
    for key, exp in refs.items():
        act = got[key]
        a = act.astype(np.float64, copy=False)
        e = exp.astype(np.float64, copy=False)
        finite = bool(np.isfinite(e).all() and np.isfinite(a).all())
        abs_max = float(np.max(np.abs(a - e))) if e.size else 0.0
        scale = float(np.max(np.abs(e))) if e.size else 0.0
        ok = finite and abs_max <= atol + rtol * scale
        print(f"[{case}] {key}: abs={abs_max:.6g} rel={rel_err(act, exp):.6g} {'OK' if ok else 'FAIL'}")
        failures += 0 if ok else 1
    return failures


def run_tool(args: list[str]) -> None:
    subprocess.run([str(TOOL), *args], cwd=ROOT, check=True)


def powlu(x1: torch.Tensor, x2: torch.Tensor, m: float) -> torch.Tensor:
    z = x2.float()
    s = torch.sigmoid(z)
    pos_mask = z > 0.0
    # Avoid inactive-branch NaN/Inf gradients at z<=0. torch.where still builds
    # both branches, so positive branch must be finite everywhere.
    zsafe = torch.where(pos_mask, z, torch.ones_like(z))
    r = torch.sqrt(zsafe)
    a = m / (r + 1.0)
    pos = torch.pow(zsafe, a) * s
    neg = z * s
    gate = torch.where(pos_mask, pos, neg)
    return (x1.float() * gate).to(x1.dtype)


def case_powlu(tmp: Path, dev: torch.device, *, seed: int, n: int, m: float) -> int:
    torch.manual_seed(seed)
    dtype = torch.float16
    x1 = (torch.randn(n, device=dev, dtype=dtype) * 0.7).requires_grad_()
    x2_data = torch.randn(n, device=dev, dtype=dtype) * 0.7
    if n >= 8:
        tiny = torch.tensor([0.0, 2.0**-24, 2.0**-20, 2.0**-14,
                             -2.0**-24, -2.0**-20, -2.0**-14, 1.0],
                            device=dev, dtype=dtype)
        x2_data[:8] = tiny
    x2 = x2_data.requires_grad_()
    go = torch.randn(n, device=dev, dtype=dtype) * 0.03
    out = powlu(x1, x2, m)
    (out.float() * go.float()).sum().backward()

    write_raw(tmp, "x1", x1.detach().cpu().numpy())
    write_raw(tmp, "x2", x2.detach().cpu().numpy())
    write_raw(tmp, "go", go.detach().cpu().numpy())
    run_tool(["powlu", str(tmp), str(n), str(m)])
    refs = {
        "out": out.detach().cpu().numpy(),
        "grad_x1": x1.grad.detach().cpu().numpy(),
        "grad_x2": x2.grad.detach().cpu().numpy(),
    }
    got = {
        "out": read_raw(tmp, "out", np.float16, (n,)),
        "grad_x1": read_raw(tmp, "grad_x1", np.float32, (n,)),
        "grad_x2": read_raw(tmp, "grad_x2", np.float32, (n,)),
    }
    return compare_arrays(f"powlu_n{n}_m{m:g}", refs, got, 1e-4, 1e-4)


def case_lmce(tmp: Path, dev: torch.device, *, seed: int, rows: int, d: int,
              vocab: int, ignore_frac: float, has_ignore: bool) -> int:
    torch.manual_seed(seed)
    dtype = torch.float16
    ignore_index = -100
    hidden = (torch.randn(rows, d, device=dev, dtype=dtype) * 0.2).requires_grad_()
    weight = (torch.randn(vocab, d, device=dev, dtype=dtype) * 0.08).requires_grad_()
    targets = torch.randint(0, vocab, (rows,), device=dev, dtype=torch.long)
    if has_ignore and ignore_frac > 0.0:
        ignore = torch.rand(rows, device=dev) < ignore_frac
        targets[ignore] = ignore_index
    logits = hidden.float() @ weight.float().t()
    loss = F.cross_entropy(logits, targets, ignore_index=ignore_index, reduction="mean")
    loss.backward()

    write_raw(tmp, "hidden", hidden.detach().cpu().numpy())
    write_raw(tmp, "weight", weight.detach().cpu().numpy())
    write_raw(tmp, "targets", targets.detach().cpu().numpy().astype(np.int32))
    run_tool(["lmce", str(tmp), str(rows), str(d), str(vocab), str(ignore_index), "1" if has_ignore else "0"])
    refs = {
        "loss": np.array([loss.detach().cpu().item()], dtype=np.float32),
        "grad_hidden": hidden.grad.detach().cpu().numpy(),
        "grad_weight": weight.grad.detach().cpu().numpy(),
    }
    got = {
        "loss": read_raw(tmp, "loss", np.float32, (1,)),
        "grad_hidden": read_raw(tmp, "grad_hidden", np.float32, (rows, d)),
        "grad_weight": read_raw(tmp, "grad_weight", np.float32, (vocab, d)),
    }
    suffix = "ignore" if has_ignore else "noignore"
    return compare_arrays(f"lmce_{rows}x{d}_v{vocab}_{suffix}", refs, got, 1e-3, 1e-3)


def case_rms_norm_qkv(tmp: Path, dev: torch.device, *, seed: int, rows: int, d: int,
                      qn: int, kn: int, vn: int, eps: float) -> int:
    torch.manual_seed(seed)
    dtype = torch.float16
    x = (torch.randn(rows, d, device=dev, dtype=dtype) * 0.7).requires_grad_()
    gamma = (1.0 + 0.01 * torch.randn(d, device=dev, dtype=dtype)).requires_grad_()
    wq = (torch.randn(d, qn, device=dev, dtype=dtype) * 0.08).requires_grad_()
    wk = (torch.randn(d, kn, device=dev, dtype=dtype) * 0.08).requires_grad_()
    wv = (torch.randn(d, vn, device=dev, dtype=dtype) * 0.08).requires_grad_()
    inv = torch.rsqrt(x.float().pow(2).mean(dim=-1, keepdim=True) + eps)
    norm = (x.float() * inv * gamma.float()).to(dtype)
    q = (norm.float() @ wq.float()).to(dtype)
    k = (norm.float() @ wk.float()).to(dtype)
    v = (norm.float() @ wv.float()).to(dtype)
    go_norm = torch.randn_like(norm) * 0.02
    go_q = torch.randn_like(q) * 0.02
    go_k = torch.randn_like(k) * 0.02
    go_v = torch.randn_like(v) * 0.02
    loss = (norm.float() * go_norm.float()).sum()
    loss = loss + (q.float() * go_q.float()).sum()
    loss = loss + (k.float() * go_k.float()).sum()
    loss = loss + (v.float() * go_v.float()).sum()
    loss.backward()

    for name, arr in {
        "x": x, "gamma": gamma, "wq": wq, "wk": wk, "wv": wv,
        "go_norm": go_norm, "go_q": go_q, "go_k": go_k, "go_v": go_v,
    }.items():
        write_raw(tmp, name, arr.detach().cpu().numpy())
    run_tool(["rms_norm_qkv", str(tmp), str(rows), str(d), str(qn), str(kn), str(vn), str(eps)])
    refs = {
        "out_norm": norm.detach().cpu().numpy(),
        "out_q": q.detach().cpu().numpy(),
        "out_k": k.detach().cpu().numpy(),
        "out_v": v.detach().cpu().numpy(),
        "grad_x": x.grad.detach().cpu().numpy(),
        "grad_gamma": gamma.grad.detach().cpu().numpy(),
        "grad_wq": wq.grad.detach().cpu().numpy(),
        "grad_wk": wk.grad.detach().cpu().numpy(),
        "grad_wv": wv.grad.detach().cpu().numpy(),
    }
    got = {
        "out_norm": read_raw(tmp, "out_norm", np.float16, (rows, d)),
        "out_q": read_raw(tmp, "out_q", np.float16, (rows, qn)),
        "out_k": read_raw(tmp, "out_k", np.float16, (rows, kn)),
        "out_v": read_raw(tmp, "out_v", np.float16, (rows, vn)),
        "grad_x": read_raw(tmp, "grad_x", np.float32, (rows, d)),
        "grad_gamma": read_raw(tmp, "grad_gamma", np.float32, (d,)),
        "grad_wq": read_raw(tmp, "grad_wq", np.float32, (d, qn)),
        "grad_wk": read_raw(tmp, "grad_wk", np.float32, (d, kn)),
        "grad_wv": read_raw(tmp, "grad_wv", np.float32, (d, vn)),
    }
    return compare_arrays(f"rms_norm_qkv_{rows}x{d}_{qn}_{kn}_{vn}", refs, got, 2e-3, 2e-3)


def allowed(i: torch.Tensor, j: torch.Tensor, causal: bool, window: int, prefix_len: int) -> torch.Tensor:
    ok = torch.ones((i.numel(), j.numel()), device=i.device, dtype=torch.bool)
    ii = i[:, None]
    jj = j[None, :]
    if causal:
        if prefix_len > 0:
            ok &= torch.where(ii < prefix_len, jj < prefix_len, jj <= ii)
        else:
            ok &= jj <= ii
    if window > 0:
        if prefix_len > 0:
            ok &= torch.where((ii >= prefix_len) & (jj >= prefix_len), (ii - jj) < window, True)
        else:
            ok &= (ii - jj) < window
    return ok


def sdpa_varlen(q: torch.Tensor, k: torch.Tensor, v: torch.Tensor, cu: torch.Tensor,
                scale: float, causal: bool, window: int, prefix_len: int) -> torch.Tensor:
    outs = []
    hq = q.shape[1]
    hkv = k.shape[1]
    group = hq // hkv
    for b in range(cu.numel() - 1):
        lo = int(cu[b].item())
        hi = int(cu[b + 1].item())
        tq = hi - lo
        pos = torch.arange(tq, device=q.device)
        mask = allowed(pos, pos, causal, window, prefix_len)
        for h in range(hq):
            hk = h // group
            scores = (q[lo:hi, h].float() @ k[lo:hi, hk].float().t()) * scale
            scores = scores.masked_fill(~mask, -torch.inf)
            probs = torch.softmax(scores, dim=-1)
            outs.append((probs @ v[lo:hi, hk].float()).to(q.dtype))
    out = torch.empty_like(q)
    idx = 0
    for b in range(cu.numel() - 1):
        lo = int(cu[b].item())
        hi = int(cu[b + 1].item())
        for h in range(hq):
            out[lo:hi, h] = outs[idx]
            idx += 1
    return out


def case_sdpa_varlen(tmp: Path, dev: torch.device, *, seed: int, lengths: list[int],
                     hq: int, hkv: int, dh: int, causal: bool, window: int,
                     prefix_len: int, scale: float | None) -> int:
    torch.manual_seed(seed)
    dtype = torch.float16
    total = sum(lengths)
    scale_value = scale if scale is not None else 1.0 / math.sqrt(dh)
    q = (torch.randn(total, hq, dh, device=dev, dtype=dtype) * 0.25).requires_grad_()
    k = (torch.randn(total, hkv, dh, device=dev, dtype=dtype) * 0.25).requires_grad_()
    v = (torch.randn(total, hkv, dh, device=dev, dtype=dtype) * 0.25).requires_grad_()
    cu = torch.tensor([0] + list(np.cumsum(lengths)), device=dev, dtype=torch.int32)
    go = torch.randn_like(q) * 0.02
    out = sdpa_varlen(q, k, v, cu, scale_value, causal, window, prefix_len)
    (out.float() * go.float()).sum().backward()

    for name, arr in {"q": q, "k": k, "v": v, "go": go}.items():
        write_raw(tmp, name, arr.detach().cpu().numpy())
    write_raw(tmp, "cu", cu.detach().cpu().numpy())
    max_seq = max(lengths)
    c_scale = 0.0 if scale is None else scale_value
    run_tool(["sdpa_varlen", str(tmp), str(total), str(len(lengths)), str(hq), str(hkv), str(dh),
              "1" if causal else "0", str(window), str(prefix_len), str(max_seq), str(c_scale)])
    refs = {
        "out": out.detach().cpu().numpy(),
        "grad_q": q.grad.detach().cpu().numpy(),
        "grad_k": k.grad.detach().cpu().numpy(),
        "grad_v": v.grad.detach().cpu().numpy(),
    }
    got = {
        "out": read_raw(tmp, "out", np.float16, (total, hq, dh)),
        "grad_q": read_raw(tmp, "grad_q", np.float32, (total, hq, dh)),
        "grad_k": read_raw(tmp, "grad_k", np.float32, (total, hkv, dh)),
        "grad_v": read_raw(tmp, "grad_v", np.float32, (total, hkv, dh)),
    }
    return compare_arrays(f"sdpa_varlen_len{'-'.join(map(str, lengths))}_h{hq}_{hkv}_dh{dh}", refs, got, 2e-3, 2e-3)


def build_cases(selected: set[str]) -> list[Case]:
    all_cases = [
        Case("powlu_branch", "powlu", lambda tmp, dev: case_powlu(tmp, dev, seed=123, n=4096, m=3.0)),
        Case("powlu_m2", "powlu", lambda tmp, dev: case_powlu(tmp, dev, seed=321, n=1024, m=2.0)),
        Case("lmce_ignore", "lmce", lambda tmp, dev: case_lmce(tmp, dev, seed=123, rows=257, d=64, vocab=211, ignore_frac=0.35, has_ignore=True)),
        Case("lmce_noignore", "lmce", lambda tmp, dev: case_lmce(tmp, dev, seed=321, rows=33, d=17, vocab=29, ignore_frac=0.0, has_ignore=False)),
        Case("rms_norm_qkv_square", "rms_norm_qkv", lambda tmp, dev: case_rms_norm_qkv(tmp, dev, seed=123, rows=17, d=32, qn=32, kn=32, vn=32, eps=1e-5)),
        Case("rms_norm_qkv_rect", "rms_norm_qkv", lambda tmp, dev: case_rms_norm_qkv(tmp, dev, seed=456, rows=9, d=24, qn=16, kn=8, vn=20, eps=1e-5)),
        Case("sdpa_varlen_prefix", "sdpa_varlen", lambda tmp, dev: case_sdpa_varlen(tmp, dev, seed=123, lengths=[7, 11, 13], hq=4, hkv=4, dh=32, causal=True, window=5, prefix_len=3, scale=None)),
        Case("sdpa_varlen_gqa_dh64", "sdpa_varlen", lambda tmp, dev: case_sdpa_varlen(tmp, dev, seed=456, lengths=[5, 7], hq=4, hkv=2, dh=64, causal=True, window=4, prefix_len=2, scale=None)),
    ]
    if "all" in selected:
        return all_cases
    return [c for c in all_cases if c.op in selected or c.name in selected]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cpu", help="PyTorch reference device; default cpu")
    ap.add_argument("--op", action="append", default=None,
                    help="op or case to run; repeatable. choices include powlu,lmce,rms_norm_qkv,sdpa_varlen")
    ap.add_argument("--skip-build", action="store_true")
    ap.add_argument("--keep-tmp", action="store_true")
    args = ap.parse_args()

    if not args.skip_build:
        subprocess.run(["make", "tools"], cwd=ROOT, check=True)
    if not TOOL.exists():
        raise FileNotFoundError(TOOL)

    dev = pick_device(args.device)
    selected = set(args.op or ["all"])
    cases = build_cases(selected)
    if not cases:
        print(f"no cases matched {sorted(selected)}")
        return 1

    failures = 0
    for case in cases:
        with tempfile.TemporaryDirectory(prefix=f"gd-{case.name}-") as td:
            tmp = Path(td)
            failures += case.run(tmp, dev)
            if args.keep_tmp:
                keep = Path("/tmp") / f"{case.name}-last"
                subprocess.run(["rm", "-rf", str(keep)], check=True)
                subprocess.run(["cp", "-R", str(tmp), str(keep)], check=True)
                print(f"[{case.name}] kept {keep}")
    if failures:
        print(f"FAILURES {failures}")
    else:
        print("fp16 torch refs: ok")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
