#ifndef GD_OP_KIND_H
#define GD_OP_KIND_H

/* @generated by tools/gen_ops.c; do not edit. */
typedef enum gd_op_kind {
    GD_OP_INVALID = 0,
    GD_OP_MATMUL = 1,
    GD_OP_LINEAR = 2,
    GD_OP_RELU = 3,
    GD_OP_ADD = 4,
    GD_OP_MUL = 5,
    GD_OP_SUB = 6,
    GD_OP_REDUCE_MEAN = 7,
    GD_OP_REDUCE_SUM = 8,
    GD_OP_CROSS_ENTROPY = 9,
    GD_OP_SIGMOID = 10,
    GD_OP_MSE = 11,
    GD_OP_HUBER = 12,
    GD_OP_DROPOUT = 13,
    GD_OP_SDPA_DECODE = 14,
    GD_OP_SDPA_VARLEN = 15,
    GD_OP_CONCAT = 16,
    GD_OP_RESHAPE = 17,
    GD_OP_PERMUTE = 18,
    GD_OP_SPLIT = 19,
    GD_OP_RMS_NORM = 20,
    GD_OP_ROPE = 21,
    GD_OP_EMBEDDING = 22,
    GD_OP_LINEAR_TRANSPOSED_WEIGHT = 23,
    GD_OP_POWLU = 24,
    GD_OP_KV_CACHE_APPEND = 25,
    GD_OP_LM_CROSS_ENTROPY = 26,
    GD_OP_QKV_SPLIT_ROPE = 27,
    GD_OP_POWLU_SPLIT_LINEAR = 28,
    GD_OP_TANH = 29,
    GD_OP_COUNT = 30,
} gd_op_kind;

#endif /* GD_OP_KIND_H */
