#include "autograd_impl.h"

/* @generated by tools/gen_ops.c; do not edit. */
extern const gd_autograd_rule gd_bwd_rule_matmul;
extern const gd_autograd_rule gd_bwd_rule_linear;
extern const gd_autograd_rule gd_bwd_rule_relu;
extern const gd_autograd_rule gd_bwd_rule_add;
extern const gd_autograd_rule gd_bwd_rule_mul;
extern const gd_autograd_rule gd_bwd_rule_sub;
extern const gd_autograd_rule gd_bwd_rule_reduce_mean;
extern const gd_autograd_rule gd_bwd_rule_reduce_sum;
extern const gd_autograd_rule gd_bwd_rule_cross_entropy;
extern const gd_autograd_rule gd_bwd_rule_sigmoid;
extern const gd_autograd_rule gd_bwd_rule_mse;
extern const gd_autograd_rule gd_bwd_rule_huber;
extern const gd_autograd_rule gd_bwd_rule_dropout;
extern const gd_autograd_rule gd_bwd_rule_sdpa_varlen;
extern const gd_autograd_rule gd_bwd_rule_concat;
extern const gd_autograd_rule gd_bwd_rule_reshape;
extern const gd_autograd_rule gd_bwd_rule_permute;
extern const gd_autograd_rule gd_bwd_rule_split;
extern const gd_autograd_rule gd_bwd_rule_rms_norm;
extern const gd_autograd_rule gd_bwd_rule_rope;
extern const gd_autograd_rule gd_bwd_rule_embedding;
extern const gd_autograd_rule gd_bwd_rule_linear_transposed_weight;
extern const gd_autograd_rule gd_bwd_rule_powlu;
extern const gd_autograd_rule gd_bwd_rule_lm_cross_entropy;
extern const gd_autograd_rule gd_bwd_rule_qkv_split_rope;
extern const gd_autograd_rule gd_bwd_rule_powlu_split_linear;
extern const gd_autograd_rule gd_bwd_rule_tanh;

static const gd_autograd_rule *const gd_bwd_rules[GD_OP_COUNT] = {
    [GD_OP_MATMUL] = &gd_bwd_rule_matmul,
    [GD_OP_LINEAR] = &gd_bwd_rule_linear,
    [GD_OP_RELU] = &gd_bwd_rule_relu,
    [GD_OP_ADD] = &gd_bwd_rule_add,
    [GD_OP_MUL] = &gd_bwd_rule_mul,
    [GD_OP_SUB] = &gd_bwd_rule_sub,
    [GD_OP_REDUCE_MEAN] = &gd_bwd_rule_reduce_mean,
    [GD_OP_REDUCE_SUM] = &gd_bwd_rule_reduce_sum,
    [GD_OP_CROSS_ENTROPY] = &gd_bwd_rule_cross_entropy,
    [GD_OP_SIGMOID] = &gd_bwd_rule_sigmoid,
    [GD_OP_MSE] = &gd_bwd_rule_mse,
    [GD_OP_HUBER] = &gd_bwd_rule_huber,
    [GD_OP_DROPOUT] = &gd_bwd_rule_dropout,
    [GD_OP_SDPA_VARLEN] = &gd_bwd_rule_sdpa_varlen,
    [GD_OP_CONCAT] = &gd_bwd_rule_concat,
    [GD_OP_RESHAPE] = &gd_bwd_rule_reshape,
    [GD_OP_PERMUTE] = &gd_bwd_rule_permute,
    [GD_OP_SPLIT] = &gd_bwd_rule_split,
    [GD_OP_RMS_NORM] = &gd_bwd_rule_rms_norm,
    [GD_OP_ROPE] = &gd_bwd_rule_rope,
    [GD_OP_EMBEDDING] = &gd_bwd_rule_embedding,
    [GD_OP_LINEAR_TRANSPOSED_WEIGHT] = &gd_bwd_rule_linear_transposed_weight,
    [GD_OP_POWLU] = &gd_bwd_rule_powlu,
    [GD_OP_LM_CROSS_ENTROPY] = &gd_bwd_rule_lm_cross_entropy,
    [GD_OP_QKV_SPLIT_ROPE] = &gd_bwd_rule_qkv_split_rope,
    [GD_OP_POWLU_SPLIT_LINEAR] = &gd_bwd_rule_powlu_split_linear,
    [GD_OP_TANH] = &gd_bwd_rule_tanh,
};

const gd_autograd_rule *gd_autograd_rule_for(gd_op_kind kind)
{
    if (kind <= GD_OP_INVALID || kind >= GD_OP_COUNT) {
        return NULL;
    }
    return gd_bwd_rules[kind];
}
