#include "autograd_impl.h"

/* @generated by tools/gen_ops.c; do not edit. */
extern const gd_autograd_rule gd_bwd_rule_matmul;
extern const gd_autograd_rule gd_bwd_rule_linear;
extern const gd_autograd_rule gd_bwd_rule_relu;

static const gd_autograd_rule *const gd_bwd_rules[GD_OP_COUNT] = {
    [GD_OP_MATMUL] = &gd_bwd_rule_matmul,
    [GD_OP_LINEAR] = &gd_bwd_rule_linear,
    [GD_OP_RELU] = &gd_bwd_rule_relu,
};

const gd_autograd_rule *gd_autograd_rule_for(gd_op_kind kind)
{
    if (kind <= GD_OP_INVALID || kind >= GD_OP_COUNT) {
        return NULL;
    }
    return gd_bwd_rules[kind];
}
