#include "autograd_impl.h"

/* @generated by tools/gen_ops.c; do not edit. */
extern const gd_autograd_rule gd_bwd_rule_matmul;
extern const gd_autograd_rule gd_bwd_rule_linear;
extern const gd_autograd_rule gd_bwd_rule_relu;
extern const gd_autograd_rule gd_bwd_rule_add;
extern const gd_autograd_rule gd_bwd_rule_mul;
extern const gd_autograd_rule gd_bwd_rule_sub;
extern const gd_autograd_rule gd_bwd_rule_reduce_mean;
extern const gd_autograd_rule gd_bwd_rule_reduce_sum;
extern const gd_autograd_rule gd_bwd_rule_cross_entropy;

static const gd_autograd_rule *const gd_bwd_rules[GD_OP_COUNT] = {
    [GD_OP_MATMUL] = &gd_bwd_rule_matmul,
    [GD_OP_LINEAR] = &gd_bwd_rule_linear,
    [GD_OP_RELU] = &gd_bwd_rule_relu,
    [GD_OP_ADD] = &gd_bwd_rule_add,
    [GD_OP_MUL] = &gd_bwd_rule_mul,
    [GD_OP_SUB] = &gd_bwd_rule_sub,
    [GD_OP_REDUCE_MEAN] = &gd_bwd_rule_reduce_mean,
    [GD_OP_REDUCE_SUM] = &gd_bwd_rule_reduce_sum,
    [GD_OP_CROSS_ENTROPY] = &gd_bwd_rule_cross_entropy,
};

const gd_autograd_rule *gd_autograd_rule_for(gd_op_kind kind)
{
    if (kind <= GD_OP_INVALID || kind >= GD_OP_COUNT) {
        return NULL;
    }
    return gd_bwd_rules[kind];
}
